import {sendMessage} from "./sendMessage";

export function sayHello() {
	const messagesHello: string[] = [
		"Salut tout le monde ! :smiley: Passez une super journée !",
		"Bonjour à tous ! :sun_with_face: Comment ça va aujourd’hui ?",
		"Hey hey hey ! :grinning: J’espère que vous allez bien !",
		"Yo les amis ! :tada: On se réveille en douceur ?",
		"Coucou tout le monde ! :heart: Prêts pour une belle journée ?",
		"Hello ! :star: J’espère que tout roule pour vous !",
		"Wesh la team ! :sunglasses: Prêts à en découdre avec la journée ?",
		"Salut à tous ! :trophy: Aujourd’hui, c’est une bonne journée pour réussir !",
		"Bonjour, bonjour ! :sparkling_heart: Prenez soin de vous et hydratez-vous !",
		":wave: Salut les amis ! J’espère que vous avez la patate ! :potato:",
		"Yo ! :rocket: Que la force soit avec vous aujourd’hui !",
		"Hello tout le monde ! :fox: Passez une journée aussi géniale que vous !",
		"Bonjour à tous ! :coffee: Café en main, c’est parti pour une belle journée !",
		"Salut bande de pixels ! :video_game: Que votre journée soit remplie de GG !",
		"Holà ! :ocean: Une nouvelle journée commence, let's gooo !",
		"Hey ! Vous êtes magnifiques aujourd’hui ! :partying_face:",
		"Salut les loulous ! :dog: Qui veut des câlins virtuels ? :hugging:",
		"Bonjour la commu ! :earth_africa: Un max de good vibes pour vous !",
		"Yo yo yo ! :microphone: Une nouvelle journée, un nouveau défi !",
		"Hello ! :star_struck: Petit message pour vous rappeler que vous êtes géniaux !",
		"Coucou les amis ! :rainbow: Souriez, aujourd’hui c’est une belle journée !",
		"Bonjour à tous ! :four_leaf_clover: Je vous envoie plein de chance et de bonnes ondes !",
		"Heyy ! :bicyclist: Prêts à foncer dans cette nouvelle journée ?",
		"Salut la team Discord ! :speech_balloon: Que de la bonne humeur ici !",
		"Hello tout le monde ! :beach: Un café et c’est reparti !",
		"Bon matin les amis ! :sunrise: On se motive pour cette belle journée !",
		":musical_note: Bonjour, bonjour, bonjour :musical_note: (oui, c’est moi qui chante :rofl:)",
		"YOLO les gens ! :fire: Faites de votre mieux aujourd’hui !",
		":eyes: Qui a oublié de dire bonjour ? Pas moi en tout cas ! :joy:",
		"Salut tout le monde ! :wave: Comment ça va aujourd’hui ?",
		"Bonjour la commu ! :partying_face: J’espère que vous êtes en forme !",
		"Yo les gens ! :fire: Prêts pour une nouvelle journée épique ?",
		"Coucou les amis ! :heartpulse: Prenez soin de vous aujourd’hui !",
		"Hello tout le monde ! :coffee: Qui veut un petit café pour bien commencer la journée ?",
		"Salut la team ! :muscle: On attaque cette journée avec motivation !",
		"Hey hey hey ! :rocket: Une nouvelle aventure nous attend !",
		"Wesh Discord ! :sunglasses: Qui est chaud aujourd’hui ?",
		"Bonjour les amis ! :sun_with_face: J’espère que vous avez bien dormi !",
		"Yo ! :zap: Du fun et de la bonne humeur, c’est parti !",
		"Salut tout le monde ! :hugging: N’oubliez pas de sourire aujourd’hui !",
		"Holà les amis ! :tada: Que du positif pour vous aujourd’hui !",
		"Hey ! :ghost: Y a-t-il des fantômes qui dorment encore ? Réveillez-vous !",
		"Hello les gens ! :star_struck: Une bonne journée commence !",
		"Yo yo yo ! :loudspeaker: Le bot est réveillé, et vous ?",
		"Bonjour à tous ! :smiling_face_with_3_hearts: Une belle journée en perspective !",
		"Wesh la mif ! :sparkles: Que du love pour vous aujourd’hui !",
		"Coucou la commu ! :crescent_moon: Qui a fait une nuit blanche encore ? :eyes:",
		"Hello ! :upside_down: Un bonjour tout doux pour bien commencer la journée !",
		"Salut la team ! :busts_in_silhouette: Quelqu’un est réveillé ici ?",
		"Salut les noobs ! :video_game: Aujourd’hui, on farm la bonne humeur !",
		"Yo les légendes ! :crown: Encore une journée pour briller !",
		"Bonjour à tous ! :cherry_blossom: Du love et des bonnes vibes pour tout le monde !",
		"Wesh ! :nerd: Encore un jour où on va tous carry la journée !",
		"Salut Discord ! :speech_balloon: Je suis là pour répandre la bonne humeur !",
		"Bonjour, bonjour ! :sunrise: Qui est chaud pour attaquer cette journée ?",
		"Hey ! :beer: Levez la main si vous avez déjà envie du week-end ! :raised_hand:",
		"Yo ! :eyes: J’ai vu quelqu’un ne pas dire bonjour… On t’a repéré ! :rofl:",
		"Coucou les amis ! :hibiscus: Un max de good vibes pour tout le monde !",
		"Salut bande de dormeurs ! :sleeping: Réveillez-vous, c’est l’heure !",
		"Holà tout le monde ! :ocean: On surfe sur la vague du bonheur aujourd’hui !",
		"Bonjour ! :shamrock: Aujourd’hui, c’est une bonne journée, je le sens !",
		"Yo la commu ! :crossed_swords: Un bonjour guerrier pour attaquer la journée !",
		"Hello, hello ! :globe_with_meridians: Du fun et de l’amour pour tout le monde !",
		"Hey hey ! :trophy: Une journée de gagnant commence maintenant !",
		"Salut à tous ! :high_brightness: Prenez un moment pour respirer et sourire !",
		"Yo ! :boom: Vous êtes prêts à exploser cette journée ?",
		"Salut les boss ! :crown: Que cette journée vous soit favorable !",
		"Bonjour à tous ! :peach: Restez sweet et positive aujourd’hui !",
		"Hey ! :wind_blowing_face: Un petit vent de motivation pour vous !",
		"Coucou ! :seedling: On plante de bonnes vibes pour récolter du bonheur !",
		"Salut les survivants ! :zombie: Qui a survécu à la nuit ?",
		"Hello Discord ! :earth_americas: Le monde vous appartient aujourd’hui !",
		"Bonjour les amis ! :banana: Gardez la banane toute la journée !",
		"Yo la team ! :dart: Objectif du jour : rester positif et motivé !",
		"Hey ! :penguin: Petit pingouin motivé vous souhaite une belle journée !",
		"Bonjour tout le monde ! :wave:",
		"Salut à tous, j’espère que vous passez une bonne journée ! :sun_with_face:",
		"Hello la commu ! :slight_smile:",
		"Bonjour à tous ! J’espère que vous allez bien. :coffee:",
		"Yo ! J’espère que tout se passe bien pour vous aujourd’hui. :wink:",
		"Salut tout le monde, une nouvelle journée commence ! :blush:",
		"Hello ! Passez une excellente journée ! :sunny:",
		"Bonjour, bonjour ! Prenez soin de vous aujourd’hui. :sparkles:",
		"Salut ! Un message pour vous souhaiter une belle journée. :smiley:",
		"Hey tout le monde, j’espère que la journée démarre bien ! :thumbsup:",
		"Yo ! J’espère que vous êtes en forme aujourd’hui ! :muscle:",
		"Bonjour à tous, profitez bien de votre journée. :relieved:",
		"Hello tout le monde ! Que du positif aujourd’hui ! :star:",
		"Coucou ! Passez une bonne journée et prenez du temps pour vous. :herb:",
		"Salut la team ! Du courage et de la motivation pour la journée. :rocket:",
		"Bonjour ! J’espère que votre journée sera aussi lumineuse que vous. :sunrise:",
		"Hello à tous ! On attaque cette journée avec énergie. :zap:",
		"Salut les amis ! Que votre journée soit agréable et paisible. :dove:",
		"Bonjour à vous ! J’espère que tout roule aujourd’hui. :seedling:",
		"Yo ! Une nouvelle journée, de nouvelles opportunités. :four_leaf_clover:",
		"Hey ! Passez une bonne journée et restez motivés. :fire:",
		"Bonjour tout le monde ! Que de la bonne humeur pour aujourd’hui ! :sparkling_heart:",
		"Salut à tous, prenez un instant pour respirer et apprécier la journée. :deciduous_tree:",
		"Hello ! Un petit message pour vous envoyer de bonnes ondes. :wave:",
		"Yo ! Faites de votre mieux aujourd’hui, c’est tout ce qui compte. :100:",
		"Bonjour ! Que cette journée vous apporte ce que vous souhaitez. :raised_hands:",
		"Coucou tout le monde ! Prenez soin de vous et des autres. :hearts:",
		"Hello la commu ! Une nouvelle journée, une nouvelle chance. :sunrise_over_mountains:",
		"Salut ! J’espère que cette journée sera douce et agréable. :cloud:",
		"Bonjour, bonjour ! Profitez de chaque instant. :star2:",
		"Yo ! Aujourd’hui est un bon jour pour avancer et progresser. :chart_with_upwards_trend:",
		"Salut la team ! Un café et c’est reparti ! :coffee:",
		"Hello à tous ! Gardez le sourire, ça change tout. :grinning:",
		"Bonjour tout le monde ! On reste positif et motivé ! :fist:",
		"Salut les amis ! J’espère que la journée commence bien pour vous. :raised_hands:",
		"Hey ! Une pensée positive pour bien commencer la journée. :sparkles:",
		"Bonjour ! Une nouvelle journée, une nouvelle opportunité. :dizzy:",
		"Bonjour tout le monde ! :wave:",
		"Salut à tous, j’espère que votre journée commence bien. :sun_with_face:",
		"Hello la commu, passez une belle journée ! :slight_smile:",
		"Bonjour à tous ! Prenez soin de vous aujourd’hui. :herb:",
		"Salut ! J’espère que tout se passe bien pour vous. :blush:",
		"Hello ! Un petit message pour vous souhaiter une bonne journée. :coffee:",
		"Yo ! J’espère que vous êtes en forme aujourd’hui. :muscle:",
		"Bonjour, bonjour ! Que cette journée soit douce et agréable. :sunrise:",
		"Salut tout le monde, profitez de cette journée ! :relieved:",
		"Hello à tous ! Prenez un instant pour souffler et apprécier la journée. :deciduous_tree:",
		"Bonjour ! Que du positif pour aujourd’hui ! :sparkles:",
		"Coucou ! Un petit coucou pour vous envoyer de bonnes vibes. :wave:",
		"Salut la team ! J’espère que tout roule de votre côté. :thumbsup:",
		"Bonjour tout le monde ! Que cette journée soit pleine de bonnes surprises. :four_leaf_clover:",
		"Yo ! Une nouvelle journée, un nouveau départ. :dizzy:",
		"Hello ! Gardez le sourire, ça change tout. :smiley:",
		"Bonjour à tous, que la journée vous soit légère et paisible. :cloud:",
		"Salut les amis ! Faites de votre mieux aujourd’hui. :100:",
		"Hey ! J’espère que vous passez un bon moment. :star:",
		"Bonjour ! Un café et c’est parti pour la journée ! :coffee:",
		"Salut tout le monde ! Profitez de chaque instant. :sunrise_over_mountains:",
		"Hello la commu ! Du courage et de la motivation pour aujourd’hui. :zap:",
		"Bonjour ! J’espère que tout se passe bien pour vous. :seedling:",
		"Salut à tous ! Une nouvelle journée pleine d’opportunités. :chart_with_upwards_trend:",
		"Hey ! Juste un petit message pour vous souhaiter une belle journée. :heart:",
		"Bonjour la team ! On avance un pas après l’autre. :footprints:",
		"Salut tout le monde ! Pensez à vous hydrater aujourd’hui. :droplet:",
		"Hello ! Prenez une grande inspiration et lancez-vous. :leaves:",
		"Yo ! Une journée à prendre comme elle vient. :wave:",
		"Bonjour à vous tous ! Restez zen et positif. :relieved:",
		"Salut ! Aujourd’hui, on fait de son mieux, et c’est déjà énorme. :sparkles:",
		"Hello ! Profitez de l’instant présent, c’est tout ce qui compte. :peace:",
		"Salut tout le monde, prenez le temps de souffler et de sourire. :slight_smile:",
		"Bonjour ! Un pas après l’autre, vous avancez. :footprints:",
		"Yo la commu ! Que la journée soit bonne et douce. :star2:",
		"Bonjour à tous ! Prenez un moment pour vous aujourd’hui. :herb:",
		"Hello ! Un petit coucou pour bien commencer la journée. :sun_with_face:",
		"Salut la team ! J’espère que tout se passe bien pour vous. :coffee:",
		"Bonjour tout le monde ! Une nouvelle journée commence. :sunrise:",
	];

	const randomIndex = Math.floor(Math.random() * messagesHello.length);
	sendMessage(messagesHello[randomIndex], process.env.WELCOME_CHANNEL);
}